#!/usr/bin/env bash
REGISTRY=ghcr.io/sstaehli

docker run -it \
    -e HOST_UID=$(id -u) \
    -e HOST_GID=$(id -g) \
    -v $(pwd):/workspace \
    -w /workspace \
    --rm \
    $REGISTRY/nvc-vunit:latest \
    bash -lc \
        'groupadd -g "$HOST_GID" hostgroup; useradd -m -u "$HOST_UID" -g "$HOST_GID" hostuser; \
            . /opt/venv/bin/activate && \
            exec gosu hostuser python3 "$@"' -- "$@" 